<?php
/*
Plugin Name: WPFD Stats
Description: Enhanced tracking and reporting for WP File Download that shows BOTH downloads AND previews by date.
Version: 3.3
Author: Tyler Couty
*/

if (!defined('ABSPATH')) exit;

// GitHub Updater Configuration
define('WPFD_STATS_VERSION', '3.3');
define('WPFD_STATS_GITHUB_USERNAME', 'tylercouty');
define('WPFD_STATS_GITHUB_REPO', 'wpfd-tracker');
define('WPFD_STATS_PLUGIN_FILE', __FILE__);
define('WPFD_STATS_PLUGIN_SLUG', plugin_basename(__FILE__));

/**
 * GitHub Plugin Updater Class
 */
class WPFD_Stats_GitHub_Updater {

    private $github_username;
    private $github_repo;
    private $plugin_file;
    private $plugin_slug;
    private $current_version;
    private $github_response;

    public function __construct() {
        $this->github_username = WPFD_STATS_GITHUB_USERNAME;
        $this->github_repo = WPFD_STATS_GITHUB_REPO;
        $this->plugin_file = WPFD_STATS_PLUGIN_FILE;
        $this->plugin_slug = WPFD_STATS_PLUGIN_SLUG;
        $this->current_version = WPFD_STATS_VERSION;

        add_filter('pre_set_site_transient_update_plugins', array($this, 'check_for_update'));
        add_filter('plugins_api', array($this, 'plugin_info'), 10, 3);
        add_filter('upgrader_post_install', array($this, 'after_install'), 10, 3);
        add_filter('plugin_row_meta', array($this, 'plugin_row_meta'), 10, 2);
    }

    /**
     * Get repository info from GitHub API
     */
    private function get_github_release_info() {
        if (!empty($this->github_response)) {
            return $this->github_response;
        }

        $request_uri = sprintf(
            'https://api.github.com/repos/%s/%s/releases/latest',
            $this->github_username,
            $this->github_repo
        );

        $response = wp_remote_get($request_uri, array(
            'headers' => array(
                'Accept' => 'application/vnd.github.v3+json',
                'User-Agent' => 'WordPress/' . get_bloginfo('version')
            )
        ));

        if (is_wp_error($response) || wp_remote_retrieve_response_code($response) !== 200) {
            return false;
        }

        $this->github_response = json_decode(wp_remote_retrieve_body($response));
        return $this->github_response;
    }

    /**
     * Check for plugin updates
     */
    public function check_for_update($transient) {
        if (empty($transient->checked)) {
            return $transient;
        }

        $release = $this->get_github_release_info();

        if (!$release) {
            return $transient;
        }

        // Get version from tag (remove 'v' prefix if present)
        $github_version = ltrim($release->tag_name, 'v');

        if (version_compare($github_version, $this->current_version, '>')) {
            // Find the zip asset
            $download_url = $this->get_download_url($release);

            if ($download_url) {
                $transient->response[$this->plugin_slug] = (object) array(
                    'slug' => dirname($this->plugin_slug),
                    'plugin' => $this->plugin_slug,
                    'new_version' => $github_version,
                    'url' => $release->html_url,
                    'package' => $download_url,
                    'icons' => array(),
                    'banners' => array(),
                    'tested' => get_bloginfo('version'),
                    'requires_php' => '7.4',
                );
            }
        }

        return $transient;
    }

    /**
     * Get download URL from release
     */
    private function get_download_url($release) {
        // First, check for a zip asset in the release assets
        if (!empty($release->assets)) {
            foreach ($release->assets as $asset) {
                if (strpos($asset->name, '.zip') !== false) {
                    return $asset->browser_download_url;
                }
            }
        }

        // Fall back to the zipball URL (auto-generated by GitHub)
        return $release->zipball_url;
    }

    /**
     * Provide plugin information for the update details popup
     */
    public function plugin_info($result, $action, $args) {
        if ($action !== 'plugin_information') {
            return $result;
        }

        if (dirname($this->plugin_slug) !== $args->slug) {
            return $result;
        }

        $release = $this->get_github_release_info();

        if (!$release) {
            return $result;
        }

        $github_version = ltrim($release->tag_name, 'v');

        $plugin_data = get_plugin_data($this->plugin_file);

        return (object) array(
            'name' => $plugin_data['Name'],
            'slug' => dirname($this->plugin_slug),
            'version' => $github_version,
            'author' => $plugin_data['Author'],
            'homepage' => sprintf('https://github.com/%s/%s', $this->github_username, $this->github_repo),
            'requires' => '5.0',
            'tested' => get_bloginfo('version'),
            'requires_php' => '7.4',
            'downloaded' => 0,
            'last_updated' => $release->published_at,
            'sections' => array(
                'description' => $plugin_data['Description'],
                'changelog' => $this->parse_changelog($release->body),
            ),
            'download_link' => $this->get_download_url($release),
        );
    }

    /**
     * Parse changelog from release body (markdown)
     */
    private function parse_changelog($body) {
        if (empty($body)) {
            return 'No changelog available.';
        }

        // Convert markdown to basic HTML
        $changelog = esc_html($body);
        $changelog = nl2br($changelog);
        $changelog = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $changelog);
        $changelog = preg_replace('/\*(.*?)\*/', '<em>$1</em>', $changelog);
        $changelog = preg_replace('/^- (.*)$/m', '<li>$1</li>', $changelog);

        return '<div class="changelog">' . $changelog . '</div>';
    }

    /**
     * Rename the extracted folder after install to match plugin slug
     */
    public function after_install($response, $hook_extra, $result) {
        global $wp_filesystem;

        if (!isset($hook_extra['plugin']) || $hook_extra['plugin'] !== $this->plugin_slug) {
            return $result;
        }

        $plugin_folder = WP_PLUGIN_DIR . '/' . dirname($this->plugin_slug);

        // Move from the extracted folder (e.g., tylercouty-wpfd-tracker-abc123) to the correct folder
        $wp_filesystem->move($result['destination'], $plugin_folder);
        $result['destination'] = $plugin_folder;

        // Reactivate the plugin
        if (is_plugin_active($this->plugin_slug)) {
            activate_plugin($this->plugin_slug);
        }

        return $result;
    }

    /**
     * Add GitHub link to plugin row meta
     */
    public function plugin_row_meta($links, $file) {
        if ($file === $this->plugin_slug) {
            $links[] = sprintf(
                '<a href="%s" target="_blank">View on GitHub</a>',
                esc_url(sprintf('https://github.com/%s/%s', $this->github_username, $this->github_repo))
            );
        }
        return $links;
    }
}

// Initialize the updater
add_action('init', function() {
    if (is_admin()) {
        new WPFD_Stats_GitHub_Updater();
    }
});

/**
 * Register REST API endpoint for Google Sheets integration
 */
add_action('rest_api_init', function() {
    register_rest_route('wpfd-stats/v1', '/data', array(
        'methods' => 'GET',
        'callback' => 'wpfd_stats_api_get_data',
        'permission_callback' => '__return_true', // Public endpoint
    ));
});

/**
 * REST API callback - returns stats data as JSON
 * 
 * Parameters:
 * - months: Number of months to fetch (default: 6)
 */
function wpfd_stats_api_get_data($request) {
    global $wpdb;
    $table = get_wpfd_stats_table();
    
    // Check if table exists
    if ($wpdb->get_var("SHOW TABLES LIKE '$table'") != $table) {
        return new WP_Error('no_table', 'WPFD statistics table not found', array('status' => 404));
    }
    
    $months = intval($request->get_param('months')) ?: 6;
    $months = min($months, 24); // Cap at 24 months
    
    // Calculate date range
    $end_date = date('Y-m-d');
    $start_date = date('Y-m-d', strtotime("-{$months} months"));
    
    // Query the data - grouped by date and file
    $rows = $wpdb->get_results($wpdb->prepare("
        SELECT 
            DATE_FORMAT(date, '%%c/%%e/%%Y') as period,
            related_id as file_id,
            SUM(count) as views
        FROM $table
        WHERE date >= %s AND date <= %s
        GROUP BY date, related_id
        ORDER BY date DESC, related_id
    ", $start_date, $end_date));
    
    // Build response array
    $data = array();
    foreach ($rows as $row) {
        $data[] = array(
            'Period' => $row->period,
            'Title' => get_wpfd_file_name($row->file_id),
            'Views' => intval($row->views)
        );
    }
    
    // Return JSON response
    return new WP_REST_Response($data, 200);
}

/**
 * Helper function to get WPFD statistics table name
 */
function get_wpfd_stats_table() {
    global $wpdb;
    return $wpdb->prefix . 'wpfd_statistics';
}

/**
 * Helper function to get file name from WPFD
 */
function get_wpfd_file_name($file_id) {
    $file_post = get_post($file_id);
    return $file_post ? $file_post->post_title : 'Unknown File (ID: ' . $file_id . ')';
}

/**
 * Handle CSV export BEFORE any WordPress output
 */
add_action('admin_init', function() {
    if (isset($_POST['wpfd_enhanced_export']) && isset($_POST['month']) && isset($_POST['year'])) {
        global $wpdb;
        $table = get_wpfd_stats_table();
        
        $month = intval($_POST['month']);
        $year = intval($_POST['year']);

        
    // Query WPFD's existing statistics table
$rows = $wpdb->get_results($wpdb->prepare("
    SELECT 
        related_id as file_id,
        date,
        SUM(count) as total_count
    FROM $table
    WHERE YEAR(date) = %d AND MONTH(date) = %d
    GROUP BY related_id, date
    ORDER BY date DESC, related_id
", $year, $month));

// Clean all output buffers
while (ob_get_level()) {
    ob_end_clean();
}

// Set CSV headers
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="wpfd-detailed-views-' . $year . '-' . sprintf('%02d', $month) . '.csv"');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Pragma: public');

// Output CSV
$output = fopen('php://output', 'w');

// Add BOM for Excel compatibility
fwrite($output, "\xEF\xBB\xBF");

// Data - one row per file per day
foreach ($rows as $row) {
    fputcsv($output, [
        $row->date,
        get_wpfd_file_name($row->file_id),
        $row->total_count
    ]);
}

fclose($output);
exit();
    }
});

/**
 * Add admin menu
 */
add_action('admin_menu', function() {
    add_menu_page(
        'WPFD Stats',                     // Page title
        'WPFD Stats',                     // Menu title
        'manage_options',                 // Capability
        'wpfd-enhanced-tracker',          // Slug
        'wpfd_enhanced_admin_page',       // Callback
        'dashicons-chart-bar',            // Icon
        26                                // Position (after WPFD)
    );
});

/**
 * Enhanced admin page that reads from WPFD's existing statistics
 */
function wpfd_enhanced_admin_page() {
    global $wpdb;
    $table = get_wpfd_stats_table();

    // Check if WPFD statistics table exists
    if ($wpdb->get_var("SHOW TABLES LIKE '$table'") != $table) {
        echo '<div class="wrap"><h1>WPFD Stats</h1>';
        echo '<div class="notice notice-error"><p>WP File Download statistics table not found. Make sure WP File Download is installed and activated.</p></div>';
        echo '</div>';
        return;
    }

    // Default to last full month
    $currentMonth = date('n');
    $currentYear  = date('Y');
    $defaultMonth = $currentMonth - 1;
    $defaultYear  = $currentYear;
    if ($defaultMonth < 1) {
        $defaultMonth = 12;
        $defaultYear--;
    }

    $month = isset($_POST['month']) ? intval($_POST['month']) : $defaultMonth;
    $year  = isset($_POST['year'])  ? intval($_POST['year'])  : $defaultYear;

    // Query WPFD's statistics table
    $rows = $wpdb->get_results($wpdb->prepare("
        SELECT 
            related_id as file_id,
            type,
            SUM(count) as total_count
        FROM $table
        WHERE YEAR(date) = %d AND MONTH(date) = %d
        GROUP BY related_id, type
        ORDER BY related_id, type
    ", $year, $month));

    // Process data to combine downloads and previews per file
    $file_data = array();
    foreach ($rows as $row) {
        $file_id = $row->file_id;
        if (!isset($file_data[$file_id])) {
            $file_data[$file_id] = array(
                'file_name' => get_wpfd_file_name($file_id),
                'downloads' => 0,
                'previews' => 0,
                'total' => 0
            );
        }
        
        if ($row->type == 'default') {
            $file_data[$file_id]['downloads'] = intval($row->total_count);
        } elseif ($row->type == 'preview') {
            $file_data[$file_id]['previews'] = intval($row->total_count);
        }
        
        $file_data[$file_id]['total'] = $file_data[$file_id]['downloads'] + $file_data[$file_id]['previews'];
    }

    // Sort by total views
    uasort($file_data, function($a, $b) {
        return $b['total'] - $a['total'];
    });

    // Get some debug info
    $total_records = $wpdb->get_var("SELECT COUNT(*) FROM $table");
    $recent_activity = $wpdb->get_results("
        SELECT related_id, type, date, count 
        FROM $table 
        ORDER BY date DESC 
        LIMIT 10
    ");

    // Render admin page
    ?>
    <div class="wrap">
        <h1>WPFD Stats</h1>
        <p>This page shows BOTH downloads AND previews from the WP File Download statistics.</p>

        <form method="post" style="margin-bottom:20px;">
            <label for="month">Month:</label>
            <select name="month" id="month">
                <?php for ($m=1; $m<=12; $m++): ?>
                    <option value="<?php echo $m; ?>" <?php selected($m, $month); ?>>
                        <?php echo date('F', mktime(0,0,0,$m,1)); ?>
                    </option>
                <?php endfor; ?>
            </select>

            <label for="year">Year:</label>
            <select name="year" id="year">
                <?php for ($y=date('Y'); $y>=2020; $y--): ?>
                    <option value="<?php echo $y; ?>" <?php selected($y, $year); ?>>
                        <?php echo $y; ?>
                    </option>
                <?php endfor; ?>
            </select>

            <button type="submit" name="filter" class="button">Filter</button>
            <button type="submit" name="wpfd_enhanced_export" class="button button-primary">Export Enhanced CSV</button>
        </form>

        <h2><?php echo date('F Y', mktime(0,0,0,$month,1,$year)); ?> - File Activity</h2>
        
        <?php if (!empty($file_data)): ?>
            <table class="widefat striped">
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>Total Views</th>
                        <th>Downloads</th>
                        <th>Previews</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($file_data as $data): ?>
                        <tr>
                            <td><?php echo esc_html($data['file_name']); ?></td>
                            <td><strong><?php echo $data['total']; ?></strong></td>
                            <td><?php echo $data['downloads']; ?></td>
                            <td><?php echo $data['previews']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p>No data found for this month.</p>
        <?php endif; ?>

        <div style="margin-top: 30px; border-top: 1px solid #ccc; padding-top: 20px;">
            <h3>Debug Information</h3>
            <p><strong>WPFD Statistics Table:</strong> <?php echo $table; ?></p>
            <p><strong>Total Records in WPFD Stats:</strong> <?php echo number_format($total_records); ?></p>
            
            <?php if ($recent_activity): ?>
                <p><strong>Recent Activity (Last 10 entries):</strong></p>
                <div style="background: #f9f9f9; padding: 10px; max-height: 200px; overflow-y: auto; font-size: 12px;">
                    <?php foreach ($recent_activity as $activity): ?>
                        <div>
                            <?php 
                            echo esc_html($activity->date . ' - File ID: ' . $activity->related_id . ' (' . $activity->type . ') Count: ' . $activity->count);
                            ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php else: ?>
                <p><em>No recent activity found in WPFD statistics.</em></p>
            <?php endif; ?>

            <div style="margin-top: 15px;">
                <p><strong>Raw Data Sample:</strong></p>
                <?php 
                $sample_data = $wpdb->get_results("SELECT * FROM $table LIMIT 5");
                if ($sample_data) {
                    echo '<pre style="background: #f0f0f0; padding: 10px; font-size: 11px; overflow-x: auto;">';
                    foreach ($sample_data as $row) {
                        echo "ID: {$row->id}, Related ID: {$row->related_id}, UID: {$row->uid}, Type: {$row->type}, Date: {$row->date}, Count: {$row->count}\n";
                    }
                    echo '</pre>';
                } else {
                    echo '<p><em>No sample data available.</em></p>';
                }
                ?>
            </div>
        </div>
    </div>
    <?php
}